export { default as authRoutes } from './auth-routes'
export { default as googleRoutes } from './google-routes'
export { default as passwordRecoveryRoutes } from './password-recovery-routes'
export { default as movieRoutes } from './movie-routes'
export { default as quoteRoutes } from './quote-routes'
