export { default as signUpSchema } from './signup-schema'
export { default as logInSchema } from './login-schema'
export { default as sendEmailSchema } from './send-email-schema'
export { default as googleAuthSchema } from './google-auth-schema'
export { default as recoverPasswordSchema } from './recover-password-schema'
export { default as postMovieSchema } from './post-movie-schema'
export { default as putMovieSchema } from './put-movie-schema'
